apiVersion: aws.kreintoconfigs.io/v1alpha1
kind: XVPC
metadata:
  name: eks
spec:
  parameters:
    id: platform-ref-aws
    region: us-east-1
    vpcCidrBlock: 10.0.0.0/21
    enablesecondarycidr: true
    createVpcEndpoints: true
    secondaryVpcCidrBlock: 100.99.0.0/16 
    subnets:
      - availabilityZone: us-east-1a
        type: public
        cidrBlock: 10.0.0.0/24
      - availabilityZone: us-east-1b
        type: public
        cidrBlock: 10.0.1.0/24
      - availabilityZone: us-east-1c
        type: public
        cidrBlock: 10.0.2.0/24
      - availabilityZone: us-east-1a
        type: private
        cidrBlock: 10.0.3.0/24
      - availabilityZone: us-east-1b
        type: private
        cidrBlock: 10.0.4.0/24
      - availabilityZone: us-east-1c
        type: private
        cidrBlock: 10.0.5.0/24
      - availabilityZone: us-east-1c
        type: private
        cidrBlock: 10.0.6.0/24
    # nonroutablesubnets:
    #   - availabilityZone: us-east-1a
    #     type: nrtprivate
    #     cidrBlock: 100.99.0.0/18
    #   - availabilityZone: us-east-1b
    #     type: nrtprivate
    #     cidrBlock: 100.99.64.0/18
    #   - availabilityZone: us-east-1c
    #     type: nrtprivate
    #     cidrBlock: 100.99.128.0/18
    #   - availabilityZone: us-east-1c
    #     type: nrtprivatea
    #     cidrBlock: 100.99.192.0/18
    providerConfigName: aws-provider-config